---
dependencies:
  - name: voltha
    repository: https://charts.opencord.org
    version: 2.4.6
  - name: voltha-adapter-openolt
    repository: https://charts.opencord.org
    version: 2.4.2
    alias: openolt
    condition: openolt.enabled
  - name: voltha-adapter-openonu
    repository: https://charts.opencord.org
    version: 2.3.6
    alias: openonu
    condition: openonu.enabled
